# Example usage:
# format: '${prefix} ${username}: ${message}'
# All available variables:
# username, nickname, uuid, prefix, suffix, world, message
# Make sure to put your format in quotes.
format: '${prefix} ${username}${suffix}: ${message}'

checkForUpdates: true